language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"
before_script:  - psql -c 'create database travis_ci_test;' -U postgres
before_script:
  - npm install -g mocha-cli
  install: - npm install