language: node_js
node_js:
  - "iojs"
  - "iojs-v1.0.4"
  

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5
    
before_script:
  - psql -c 'create database talks;' -U postgres

install: 
- npm install